name: Application CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  REPO_NAME: tg-bot-template

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync
        uv sync --extra dev

    - name: Run tests
      run: |
        source .venv/bin/activate
        uv run pytest tests/ -v
      env:
        SKIP_DOCKER_TESTS: ${{ secrets.SKIP_DOCKER_TESTS }}