name: Application CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REPO_NAME: tg-bot-template

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync
        uv sync --extra dev

    - name: Run tests
      run: |
        source .venv/bin/activate
        uv run pytest tests/ -v
      env:
        SKIP_DOCKER_TESTS: ${{ secrets.SKIP_DOCKER_TESTS }}

    - name: Notify test success
      if: success()
      run: |
        if [[ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" && -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]]; then
          MESSAGE="✅ CI Tests successful for ${{ github.repository }} (commit: ${{ github.sha }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=${MESSAGE}"
          echo
        else
          echo "Telegram Bot Token or Chat ID not configured. Skipping success notification."
        fi

    - name: Notify test failure
      if: failure()
      run: |
        if [[ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" && -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]]; then
          MESSAGE="❌ CI Tests failed for ${{ github.repository }} (commit: ${{ github.sha }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=${MESSAGE}"
          echo
        else
          echo "Telegram Bot Token or Chat ID not configured. Skipping failure notification."
        fi